import warnings
warnings.filterwarnings("ignore")
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Load .env file (GEMINI_API_KEY)
try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".env"))
except ImportError:
    pass

import streamlit as st
import numpy as np

st.set_page_config(
    page_title="Deep-ML Explorer",
    page_icon="🧠",
    layout="wide"
)

from problems import PROBLEM_REGISTRY
from gemini_generator import generate_with_gemini


# ── Helpers ───────────────────────────────────────────────────────────────────

def display_value(val, label=""):
    import pandas as pd
    prefix = f"**{label}:** " if label else ""
    if isinstance(val, np.ndarray):
        if val.ndim == 1:
            st.write(f"{prefix}`{np.round(val, 4).tolist()}`")
        elif val.ndim == 2:
            if label:
                st.write(f"**{label}:**")
            st.dataframe(pd.DataFrame(np.round(val, 4)), use_container_width=False)
    elif isinstance(val, float):
        st.write(f"{prefix}`{round(val, 6)}`")
    elif isinstance(val, (list, tuple)) and val:
        formatted = [round(v, 4) if isinstance(v, float) else v for v in val]
        st.write(f"{prefix}`{formatted}`")
    else:
        st.write(f"{prefix}`{val}`")


def display_answer(ans):
    if isinstance(ans, np.ndarray):
        st.success(f"✅ **Answer:** `{np.round(ans, 4).tolist()}`")
    elif isinstance(ans, float):
        st.success(f"✅ **Answer:** `{round(ans, 6)}`")
    else:
        st.success(f"✅ **Answer:** `{ans}`")


def get_api_key() -> str:
    key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not key:
        key = st.session_state.get("gemini_key", "").strip()
    return key


# ── Pre-built problem renderer ─────────────────────────────────────────────────

def render_prebuilt(prob, seed):
    example = prob["generate"](seed)
    tab1, tab2 = st.tabs(["📋 Example & Steps", "📊 Visualization"])

    with tab1:
        st.subheader("📥 Inputs")
        for k, v in example.get("inputs", {}).items():
            display_value(v, k)

        st.subheader("🔢 Step-by-Step Solution")
        for i, step in enumerate(prob["steps"](example)):
            with st.expander(f"Step {i+1}: {step['title']}", expanded=True):
                st.write(step["explanation"])
                if "math" in step:
                    st.latex(step["math"])
                if "result" in step:
                    display_value(step["result"], "Result")
                if "code" in step:
                    st.code(step["code"], language="python")

        if "answer" in example:
            display_answer(example["answer"])

    with tab2:
        import matplotlib.pyplot as plt
        fig = prob["visualize"](example)
        if fig is not None:
            st.pyplot(fig)
            plt.close(fig)
        else:
            st.info("No visualization available for this problem.")


# ── AI-generated problem renderer ─────────────────────────────────────────────

def render_ai_generated(concept: str, api_key: str):
    with st.spinner(f"Generating explanation for **{concept}**…"):
        result = generate_with_gemini(concept, api_key)

    if "error" in result:
        st.error(f"Generation failed: {result['error']}")
        return

    # Header info
    col1, col2 = st.columns([4, 1])
    col1.markdown(result.get("description", ""))
    col2.markdown(f"**Category:** {result.get('category', '—')}")
    diff_icon = {"Easy": "🟢", "Medium": "🟡", "Hard": "🔴"}.get(result.get("difficulty", ""), "⚪")
    col2.markdown(f"**Difficulty:** {diff_icon} {result.get('difficulty', '—')}")

    st.divider()

    # Inputs
    st.subheader("📥 Inputs")
    for k, v in result.get("inputs", {}).items():
        st.write(f"**{k}:** `{v}`")

    # Steps
    st.subheader("🔢 Step-by-Step Solution")
    for i, step in enumerate(result.get("steps", [])):
        with st.expander(f"Step {i+1}: {step.get('title', '')}", expanded=True):
            st.write(step.get("explanation", ""))
            if step.get("math"):
                try:
                    st.latex(step["math"])
                except Exception:
                    st.code(step["math"])
            if step.get("result"):
                st.write(f"**Result:** `{step['result']}`")
            if step.get("code"):
                st.code(step["code"], language="python")

    if result.get("answer"):
        st.success(f"✅ **Answer:** `{result['answer']}`")

    st.caption("⚡ Generated by Gemini 1.5 Flash — cached for this session")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    st.title("🧠 Deep-ML Problem Explorer")
    st.markdown(
        "*Type **any** concept from Deep-ML → get a worked example, "
        "step-by-step solution with real numbers, and a visualization.*"
    )

    # ── Sidebar ───────────────────────────────────────────────────────────────
    st.sidebar.title("🔍 Search")
    concept_input = st.sidebar.text_input(
        "Type any concept",
        placeholder="e.g. Batch Normalisation, Attention, PCA…"
    )

    st.sidebar.markdown("---")
    st.sidebar.subheader("🤖 Gemini API Key")
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        entered = st.sidebar.text_input(
            "Paste your key here",
            type="password",
            help="Get a free key at aistudio.google.com",
            key="gemini_key_input"
        )
        if entered:
            st.session_state["gemini_key"] = entered
            api_key = entered
    else:
        st.sidebar.success("✅ API key loaded from .env")

    st.sidebar.markdown("---")
    st.sidebar.subheader("📚 Pre-built Problems")
    cats = ["All"] + sorted(set(p["category"] for p in PROBLEM_REGISTRY.values()))
    cat  = st.sidebar.selectbox("Filter by category", cats)

    q = concept_input.strip().lower()
    filtered = {
        name: p for name, p in PROBLEM_REGISTRY.items()
        if (cat == "All" or p["category"] == cat)
        and (
            not q
            or q in name.lower()
            or q in p["description"].lower()
            or any(q in t.lower() for t in p.get("tags", []))
        )
    }

    # ── Routing ───────────────────────────────────────────────────────────────
    if not concept_input.strip():
        # Landing state
        st.info("👈 Type any concept name in the sidebar to get started.")
        st.markdown("### Pre-built problems (instant, no API needed):")
        for cat_name in sorted(set(p["category"] for p in PROBLEM_REGISTRY.values())):
            names = [n for n, p in PROBLEM_REGISTRY.items() if p["category"] == cat_name]
            st.markdown(f"**{cat_name}:** " + " · ".join(f"`{n}`" for n in sorted(names)))
        return

    if filtered:
        # Found in pre-built library
        best_match = sorted(
            filtered.keys(),
            key=lambda n: (0 if q in n.lower() else 1)
        )[0]

        st.sidebar.markdown(f"✅ Found in pre-built library")
        selected = st.sidebar.selectbox("Matched problems", sorted(filtered.keys()), index=sorted(filtered.keys()).index(best_match))
        seed = st.sidebar.slider("Example Seed", 0, 99, 42)

        prob = PROBLEM_REGISTRY[selected]
        diff_icon = {"Easy": "🟢", "Medium": "🟡", "Hard": "🔴"}.get(prob.get("difficulty", ""), "⚪")

        col1, col2 = st.columns([4, 1])
        col1.header(selected)
        col1.markdown(prob["description"])
        col2.markdown(f"**Category:** {prob['category']}")
        col2.markdown(f"**Difficulty:** {diff_icon} {prob.get('difficulty', '—')}")
        st.divider()

        render_prebuilt(prob, seed)

    else:
        # Not in pre-built → use Gemini
        st.header(concept_input.strip())

        if not api_key:
            st.warning(
                "This concept isn't in the pre-built library. "
                "To generate it with AI, paste your **Gemini API key** in the sidebar.\n\n"
                "Get a free key at **aistudio.google.com** (no credit card needed)."
            )
            return

        st.sidebar.info("💡 Not in library — generating with Gemini AI")
        render_ai_generated(concept_input.strip(), api_key)


if __name__ == "__main__":
    main()
